# Generated by Django 5.2 on 2025-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='reciever_name',
            field=models.CharField(default='hossam', max_length=100),
        ),
    ]
