# Generated by Django 5.2 on 2025-04-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='content',
        ),
    ]
