# Generated by Django 5.2 on 2025-04-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_notifications_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='noti_type',
            field=models.BooleanField(default=0),
        ),
    ]
