# Generated by Django 5.2 on 2025-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_notifications_noti_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='res_type',
            field=models.BooleanField(default=0),
        ),
    ]
